x'(n) = sqrt( 1 / ( y(n)^2 / x(n)^2 + 1 ) )
y'(n) = sqrt( 1 - (x'(n))^2 )

r(n+1) = r(n)/2

c(n+1) = c(n) + r(n+1) * (a > c(n) ? 1 : -1)

new_x(n) = (a > c(n)) ? (tx(n) + x'(n)) / 2 : (bx(n) + x'(n)) / 2
new_y(n) = (a > c(n)) ? (ty(n) + y'(n)) / 2 : (by(n) + y'(n)) / 2

tx(n+1) = (a > c(n)) ? tx(n) : new_x(n)
ty(n+1) = (a > c(n)) ? ty(n) : new_y(n)

bx(n+1) = (a > c(n)) ? new_x(n) : bx(n)
by(n+1) = (a > c(n)) ? new_y(n) : by(n)

x(n+1) = new_x(n)
y(n+1) = new_y(n)
